-- MySQL Script generated by MySQL Workbench
-- ter 03 out 2017 10:44:53 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Medico`

CREATE TABLE IF NOT EXISTS root(
	username varchar(40),
    pass varchar(40)
);
-- -----------------------------------------------------
use mydb;
drop table medicos;
CREATE TABLE IF NOT EXISTS `mydb`.`medicos` (
  `crm` varchar(100) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(200) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cep` VARCHAR(10) NULL,
  `complemento` VARCHAR(100) NULL,
  `cpf` VARCHAR(30) NOT NULL,
  `rg` VARCHAR(30) NOT NULL,
  `data_nascimento` VARCHAR(45) NOT NULL,
  `naturalidade` VARCHAR(30) NULL,
  `nacionalidade` VARCHAR(30) NULL,
  `email` VARCHAR(30) NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NULL,
  `trabalho` VARCHAR(45) NULL,
  `especialidades` VARCHAR(45) NULL,
  `is_active` varchar(20),
  PRIMARY KEY (`crm`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
drop table pacientes;
CREATE TABLE IF NOT EXISTS `mydb`.`pacientes` (
  `nome` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(200) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cep` VARCHAR(10) NULL,
  `complemento` VARCHAR(100) NULL,
  `cpf` VARCHAR(30) NOT NULL,
  `rg` VARCHAR(30) NOT NULL,
  `data_nascimento` VARCHAR(45) NOT NULL,
  `naturalidade` VARCHAR(30) NULL,
  `nacionalidade` VARCHAR(30) NULL,
  `email` VARCHAR(30) NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NULL,
  `trabalho` VARCHAR(45) NULL,
  `nome_pai` VARCHAR(45) NULL,
  `nome_mae` VARCHAR(45) NULL,
  `nome_sangue` VARCHAR(45) NULL,
  `is_active` varchar(20),
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;

drop table agendamentos;
CREATE TABLE IF NOT EXISTS agendamentos(
	codigo int auto_increment,
    data_agendamento varchar(45) not null,
    hora_agendamento varchar(45) not null,
    paciente VARCHAR(30) not null,
    medico varchar(100) NOT NULL,
    is_active varchar(20),
    primary key (codigo),
    foreign key (paciente) references pacientes(cpf),
    foreign key (medico) references medicos(crm)
);


CREATE TABLE IF NOT EXISTS atendimentos (
	codigo int not null auto_increment,
    p_renais varchar(40),
    p_articulares varchar(40),
    p_cardiacos varchar(40),
    p_gastriculos varchar(40),
    alergias varchar(40),
    ultiliza_med varchar(40),  
    queixas_principais varchar(800),
    hepatite varchar(10),
    gravidez varchar(10),
    diabetes varchar(10),
    cicatrização varchar(10),
    codigo_agendamento int not null,
    is_active varchar(20),
    primary key (codigo),
    foreign key (codigo_agendamento) references agendamento(codigo)
    
)ENGINE = InnoDB;
use mydb;
select * from atendimentos;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
