-- MySQL Script generated by MySQL Workbench
-- ter 03 out 2017 10:44:53 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Medico`

CREATE TABLE IF NOT EXISTS root(
	username varchar(40),
    pass varchar(40)
);
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`medicos` (
  `crm` varchar(100) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(200) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cep` VARCHAR(10) NULL,
  `complemento` VARCHAR(100) NULL,
  `cpf` VARCHAR(30) NOT NULL,
  `rg` VARCHAR(30) NOT NULL,
  `data_nascimento` VARCHAR(45) NOT NULL,
  `naturalidade` VARCHAR(30) NULL,
  `nacionalidade` VARCHAR(30) NULL,
  `email` VARCHAR(30) NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NULL,
  `trabalho` VARCHAR(45) NULL,
  `especialidades` VARCHAR(45) NULL,
  `is_active` bool,
  PRIMARY KEY (`crm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `CPF` VARCHAR(30) NOT NULL,
  `Nome_pac` VARCHAR(100) NOT NULL,
  `Endereco_pac` VARCHAR(250) NULL,
  `Bairro_pac` VARCHAR(45) NULL,
  `Cidade_pac` VARCHAR(45) NULL,
  `Estado_pac` VARCHAR(45) NULL,
  `CEP_pac` VARCHAR(10) NULL,
  `Complemento_pac` VARCHAR(50) NULL,
  `RG_pac` VARCHAR(30) NOT NULL,
  `DT_nasc_pac` VARCHAR(20) NOT NULL,
  `Naturalidade_pac` VARCHAR(45) NULL,
  `Nacionalidade_pac` VARCHAR(45) NULL,
  `Email_pac` VARCHAR(45) NULL,
  `Tel_cel` VARCHAR(45) NULL,
  `Tel_trab` VARCHAR(45) NULL,
  `Nome_pai` VARCHAR(100) NULL,
  `Nome_mae` VARCHAR(100) NULL,
  `Tipo_sangue` VARCHAR(5) NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agendamento` (
  `Cod` INT NOT NULL,
  `Data_agend` DATE NOT NULL,
  `Hora_agend` DATETIME NOT NULL,
  `Paciente_agend` VARCHAR(30) NOT NULL,
  `Medico_agend` INT NOT NULL,
  PRIMARY KEY (`Cod`),
  INDEX `Paciente_agend_idx` (`Paciente_agend` ASC),
  INDEX `Medico_gend_idx` (`Medico_agend` ASC),
  CONSTRAINT `Paciente_agend`
    FOREIGN KEY (`Paciente_agend`)
    REFERENCES `mydb`.`Paciente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Medico_gend`
    FOREIGN KEY (`Medico_agend`)
    REFERENCES `mydb`.`Medico` (`CRM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Atendimento` (
  `queixa_p` VARCHAR(500) NULL,
  `Hist` VARCHAR(100) NULL,
  `prb_renal` TINYINT(1) NULL,
  `prb_articular` TINYINT(1) NULL,
  `prb_card` TINYINT(1) NULL,
  `prb_resp` TINYINT(1) NULL,
  `prb_gast` TINYINT(1) NULL,
  `alergias` TINYINT(1) NULL,
  `hepatite` TINYINT(1) NULL,
  `gravidez` TINYINT(1) NULL,
  `diabetes` TINYINT(1) NULL,
  `prb_cicatriz` TINYINT(1) NULL,
  `utl_medicamento` TINYINT(1) NULL,
  `Agendamento_Cod` INT NOT NULL,
  PRIMARY KEY (`Agendamento_Cod`),
  CONSTRAINT `fk_agend_atend`
    FOREIGN KEY (`Agendamento_Cod`)
    REFERENCES `mydb`.`Agendamento` (`Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
